### ISSUE TITLE
Last reply link on category page

### ISSUE THREAD

**Issue by psychobunny** [NodeBB/nodebb-theme-lavender#43]
![](http://i.imgur.com/sEcWvOK.png) 

vs 

![](http://i.imgur.com/y8LYkoh.png)

This gets removed way too early as per first screenshot (md?); there's plenty of space to have all four columns, should be moved to xs instead. The topic title can span multiple lines in this design so there shouldn't be any issues really

**Comment by barisusakli** [comment]
fixed already
