### ISSUE TITLE
Custom font sizes

### ISSUE THREAD

**Issue by Couby** [NodeBB/nodebb-theme-lavender#50]
Hi,

I'd like to change the font sizes of the theme.

Following [this topic](https://community.nodebb.org/topic/2719/how-to-reduce-the-size-of-font-in-the-post-content) and using ``.topic-text`` instead of ``.post-content`` it's ok for the text in topics.

Yet the blockquote tip given in the same topic doesn't work for me. I don't find the way to change font size for quotes :-(.

Could it be possible to add somewhere (readme or wiki) how to change font sizes of the theme ? That could also be interesting for title sizes.

That could also be an improvement to give the possibility to specifically customise these elements via a custom.less or something like that ?

Thanks anyway for this great theme.

Regards.

**Comment by MegaGM** [comment]
> Yet the blockquote tip given in the same topic doesn't work for me. I don't find the way to change font size for quotes :-(

Font size rule for quotes is located in
` NodeBB/node_modules/nodebb-theme-vanilla/less/bootstrap/type.less `

You can easily find it by searching ` blockquote ` in that file

Though
> the blockquote tip given in the same topic

does work.

http://i.imgur.com/nAsBj89.png

If it doesn't work for you, you can try to force it http://i.imgur.com/VH9XwhS.png instead. But please consider, that using ` !important ` isn't a best practice. However it works just fine anyway.

**Comment by MegaGM** [comment]
> That could also be an improvement to give the possibility to specifically customise these elements via a custom.less or something like that ?

I thought it is in there, no less but css, ACP > Appearance > Custom HTML & CSS

**Comment by Couby** [comment]
You're right all works fine and custom css in ACP is ok. Sorry for this issue.
Thanks for your anwser :-)
