### ISSUE TITLE
New version of lavender does not look good.

### ISSUE THREAD

**Issue by jiangcaiyang** [NodeBB/nodebb-theme-lavender#59]
I don't know if it is CSS problem or something else, in my forum, using lavender in thread list view looks not good enough. Here is the screen shot.
I like the old rounded avatar.
![i新论坛界面不是那么好看](http://i1288.photobucket.com/albums/b485/jiangcaiyang/_zpssq5ljemk.png)

**Comment by Xuchenhao** [comment]
The same as yours

**Comment by Xuchenhao** [comment]
···
.img-rounded{
    border-radius: 100% !important;
}
.user-icon{
    border-radius: 100% !important;
}
.img-thumbnail{
    border-radius: 100% !important;
}
···
Add the code to Custom HTML & CSS ，then you will find the img is round.
![](http://moefq.com/images/2015/12/05/6ccb934cbcef405c87a211ebd2b03c98.png)

![](http://moefq.com/images/2015/12/05/bd23c83f89a7551b9fbddb8cc5716182.png)
