### ISSUE TITLE
Styling of recent topics is broken

### ISSUE THREAD

**Issue by Nisthar** [NodeBB/nodebb-theme-lavender#61]
![GitHub Logo](http://i.imgur.com/L8O4IBN.jpg)

Any solution?

**Comment by barisusakli** [comment]
Please reopen if it's still opening and give repro steps. Looks fine to me on latest with recent-cards plugin

![image](https://github.com/user-attachments/assets/aceab6b7-7ade-4a58-88f9-fc1b01db4d53)
