### ISSUE TITLE
Long post fade out (opacity change) does not seem to work with 3.0.9 and NBB1.0.2

### ISSUE THREAD

**Issue by GitPuffy** [NodeBB/nodebb-theme-lavender#69]
While testing a dev copy of my prd NodeBB forum (which is running `v0.9.4` and Lavender v 3.0.2), once I upgrade my dev to Lavender version 3.0.9 (and NodeBB `v1.0.2`) long posts on my main categories page no longer fade out (opacity change.)

Is this a change in the theme by design or possibly a bug in the new versions of Lavender and NodeBB?

Lavender 3.0.9 (NodeBB v1.0.2)
![nodebblavendernofadeout](https://cloud.githubusercontent.com/assets/16783602/13968765/256fb846-f044-11e5-9235-1cf8efa612c3.PNG)

Lavender 3.0.2 (NodeBB v0.9.4)
![nodebblavenderfadeout](https://cloud.githubusercontent.com/assets/16783602/13968774/307ffd5e-f044-11e5-9dc7-6cab92dc21ff.PNG)

**Comment by pichalite** [comment]
looks to be an issue with your installation. works fine for me on a fresh install with latest lavender.

![image](https://cloud.githubusercontent.com/assets/10014774/13970787/42f74b8c-f048-11e5-9282-811b03fb345d.png)

**Comment by GitPuffy** [comment]
I agree.  Problem with my setup.  Not sure what is causing this but it seems to only happen on one computer (but in different web browsers).
