### ISSUE TITLE
In Groups User's with Upload Photos Do Not Get user-icon class

### ISSUE THREAD

**Issue by GitPuffy** [NodeBB/nodebb-theme-lavender#71]
In Groups, it appears that user's with uploaded icon photos do not have the user-icon class assigned any longer.  Therefore I have mis-matched icons on my groups listings.  Users with the default NodeBB "letter" icon are rounded, while users that uploaded an image have square icons.

**Comment by barisusakli** [comment]
fixed in bs5 branch
