### ISSUE TITLE
Notifications panel - Text not aligned with image

### ISSUE THREAD

**Issue by GitPuffy** [NodeBB/nodebb-theme-lavender#72]
The **Notifications** panel text no longer lines up with the image.  This behavior has started since the upgrade of NodeBB from `v0.9.4 to v1.0.2`.

![nodebb-notification-panel](https://cloud.githubusercontent.com/assets/16783602/14115564/b6cfcf02-f598-11e5-9918-6f991a90bd1a.PNG)

**Comment by barisusakli** [comment]
fixed in bs5 branch 
![image](https://user-images.githubusercontent.com/2583394/196748654-53449d9a-4803-4750-9d0b-b036bfade6d9.png)
