### ISSUE TITLE
If Logged in condition is not working

### ISSUE THREAD

**Issue by elbin** [NodeBB/nodebb-theme-lavender#79]
We tried to add condition by checking logged user to show some HTML condition. Below is the code we tried in Admin > Extend > Widgets > **.tpl page. 

```
<!-- IF !loggedIn -->
	<a href="{config.relative_path}/login" class="btn btn-primary">[[category:guest-login-post]]</a>
<!-- ENDIF !loggedIn -->
```

But it didn't work. Is above code is correct?

**Comment by barisusakli** [comment]
Maybe try `config.loggedIn`

**Comment by elbin** [comment]
yes its working fine. thanks a lot :)
