### ISSUE TITLE
Admin Button not available on mobile

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-theme-lavender#81]
I noticed this while experimenting with themes...
Using the Lavender Theme, the Admin button used to access the admin panel (yourdomain.com/admin) is not visible/available when accessing the page page with a mobile device

**Comment by barisusakli** [comment]
fixed in bs5 branch

**Comment by RoiEXLab** [comment]
To be honest I did not expect this to get fixed after 5 years :D
