### ISSUE TITLE
nodebb 3.6.3 Click to follow failure

### ISSUE THREAD

**Issue by NuoManDai** [NodeBB/nodebb-theme-lavender#99]
nodebb 3.6.3 Clicking Follow failed while using the topic.
I found that the `nodeb-theme-persona` script was not imported, I tried to modify the import in the` plugin.json` file before it could be used normally.

`
	"scripts": [
		"static/lib/lavender.js",
		"../nodebb-theme-persona/public/persona.js",
		"../nodebb-theme-persona/public/modules/autohidingnavbar.js"
	]
`

**Comment by barisusakli** [comment]
@NuoManDai thanks for reporting fixed in lavender 7.1.8
